# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0828464a686649905e1ee668e33ed33da9f2fb269e50d3aa332b264efdbb1e6c01d16fec40c6cdfcdbc841121f43062dbed1869cd76ba5997cca78fab94feaf0

test:
  secret_key_base: 4a76a175b08ee2532a54cd783f001d49de1d59f8a93318989fa2d1f76afefe272a3745dfcf61c19ff22b49173ad3a654885734e992d3a1a1513c42de689e6ff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
